PB_PETS/Controllers/UsuarioController.cs
using Azure.Storage.Blobs;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using PB_PETS.Helpers;
using PB_PETS.Models;
using System.Data;

namespace PB_PETS.Controllers
{
    public class UsuarioController : Controller
    {
        private IDbConnection conexao;
        private string blobConnectionString = "DefaultEndpointsProtocol=https;AccountName=rodstorage212121;AccountKey=J65S5+UoCngu3gx1f1NDTfAxUaOMH6REVKpw6ItRjUWNLpBW2KxImHeLAk2S7e6WvJ8RSlqgPpJs+ASta9ILMg==;EndpointSuffix=core.windows.net";
        private string containerName = "containerfinalpb";
        private string bucketUrl = "https://rodstorage212121.blob.core.windows.net/containerfinalpb";
        private LoggedUser loggedUser = new LoggedUser();

        public UsuarioController(IDbConnection conexao)
        {
            this.conexao = conexao;
        }
        public ActionResult Perfil(string id)
        {
            conexao.Open();
            List<UsuarioPerfilModel> usuarios = (List<UsuarioPerfilModel>)conexao.Query<UsuarioPerfilModel>("SELECT * FROM Usuario where Id=@id", new { id = int.Parse(id) });
            conexao.Close();

        
            if (usuarios.Count > 0)
            {
                List<AmizadeModel> amizades = (List<AmizadeModel>)conexao.Query<AmizadeModel>("SELECT * FROM Amizade where IdUsuarioDestino=@id AND idUsuarioOrigem=@meuId OR IdUsuarioDestino=@meuId AND idUsuarioOrigem=@id", new { id = int.Parse(id), meuId = loggedUser.getLoggedUser() });
                var usuario = usuarios[0];

                usuario.isSolicitado = false;
                usuario.isAmigo = false;
                usuario.isMine = usuario.Id == loggedUser.getLoggedUser() ? true : false;
                if (amizades.Count > 0)
                {
                    usuario.isSolicitado = true;
                    usuario.idAmizade = 0;

                    if (amizades[0].statusDaSolicitacao != 0)
                    {
                        usuario.isAmigo = true;
                        usuario.idAmizade = amizades[0].Id;
                    }
                }
                return View(usuarios[0]);
            };
            return Redirect("/Publicacao/Listar");
        }

        public ActionResult EditarPerfil(string id)
        {
            if (int.Parse(id) != 1)
            {
                return RedirectToAction("/Publicacao/Listar");
            }
            conexao.Open();
            List<UsuarioPerfilModel> usuarios = (List<UsuarioPerfilModel>)conexao.Query<UsuarioPerfilModel>("SELECT * FROM Usuario where Id=@id", new { id = int.Parse(id) });
            conexao.Close();

            if (usuarios.Count > 0)
            {
                var usuario = usuarios[0];

                return View(usuario);
            };
            return RedirectToAction("/Publicacao/Listar");
        }

        [HttpPost]
        public ActionResult EditarPerfil(UsuarioModel usuario)
        {
            conexao.Open();
            conexao.Query<UsuarioPerfilModel>("UPDATE Usuario SET nome=@nome, sobrenome =@sobrenome, email=@email, telefone =@telefone, endereco =@endereco where Id = @Id", new
            {
                id = usuario.Id,
                nome = usuario.nome,
                sobrenome = usuario.sobrenome,
                email = usuario.email,
                telefone = usuario.telefone,
                endereco = usuario.endereco
            });
            conexao.Close();


            return Redirect("/usuario/Perfil" + "?Id=" + usuario.Id);
        }

        public ActionResult EditarSenha()
        {
            var changeSenha = new EditarSenhaModel();
            changeSenha.Id = loggedUser.getLoggedUser();
            return View(changeSenha);
        }

        [HttpPost]
        public ActionResult EditarSenha(EditarSenhaModel usuarioNovaSenha)
        {

            var changeSenha = new EditarSenhaModel();
            conexao.Open();
            List<UsuarioPerfilModel> usuarios = (List<UsuarioPerfilModel>)conexao.Query<UsuarioPerfilModel>("SELECT * FROM Usuario where Id=@id", new { id = usuarioNovaSenha.Id });
            conexao.Close();

            if (usuarios.Count == 0)
            {
                return RedirectToAction("/");
            };
            changeSenha.senhaAtual = usuarioNovaSenha.senhaAtual;
            changeSenha.senha = usuarioNovaSenha.senha;
            changeSenha.senha2 = usuarioNovaSenha.senha2;

            var usuario = usuarios[0];
            if (usuario.senha != usuarioNovaSenha.senhaAtual)
            {
                changeSenha.erroSenhaAtual = true;
                return View(changeSenha);
            }
            if (usuarioNovaSenha.senha != usuarioNovaSenha.senha2)
            {
                changeSenha.erroSenhaNova = true;
                return View(changeSenha);
            }

            conexao.Query<UsuarioPerfilModel>("UPDATE Usuario SET senha=@senha where Id = @id", new
            {
                id = usuarioNovaSenha.Id,
                senha = usuarioNovaSenha.senha
            });
            conexao.Close();


            return Redirect("/usuario/Perfil" + "?Id=" + usuario.Id);
        }

        [HttpPost]

        public async Task<ActionResult> putFoto()
        {
            var file = this.HttpContext.Request.Form.Files.FirstOrDefault();

            var dict = this.HttpContext.Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            int id = int.Parse(dict["id"]);

            var foto = "";

            if (file != null)
            {
                if (file == null)
                {
                    return BadRequest();
                }
                else if (file.ContentType != "image/jpg" && file.ContentType != "image/png" && file.ContentType != "image/jpeg" && file.ContentType != "image/bmp" && file.ContentType != "image/gif")
                {
                    return BadRequest();
                }

                using (var stream = file.OpenReadStream())
                {
                    string fileName = Guid.NewGuid().ToString("N") + "." + file.ContentType.Split('/')[1];

                    // Conecta no Azure Blob Storage
                    BlobServiceClient client = new BlobServiceClient(blobConnectionString);
                    // Pega a referencia do container
                    var containerClient = client.GetBlobContainerClient(containerName);
                    // Cria a referencia do nome do arquivo
                    BlobClient blob = containerClient.GetBlobClient(fileName);
                    // Sobe para Azure
                    await blob.UploadAsync(stream);
                    foto = $"{bucketUrl}/{fileName}";
                }
            }

            conexao.Open();
            conexao.Query<UsuarioModel>("UPDATE Usuario SET foto = @foto where Id = @idUsuario", new { idUsuario = id, foto = foto });
            conexao.Close();
            return Redirect("/usuario/EditarPerfil" + "?Id=" + id.ToString());
        }

        
         [HttpPost]
        public ActionResult deleteFoto(UsuarioModel usuario)
        {
            conexao.Open();
            conexao.Query<UsuarioPerfilModel>("UPDATE Usuario SET foto=@foto where Id =@id", new
            {
                id = usuario.Id,
                foto=""
            });
            conexao.Close();


            return Redirect("/usuario/EditarPerfil" + "?Id=" + usuario.Id);
        }

        [HttpPost]

        public ActionResult redirectPerfil()
        {
            return Redirect("/usuario/Perfil" + "?Id=" + loggedUser.getLoggedUser());

        }

        public ActionResult login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UsuarioModel usuario)
        {
            conexao.Open();
            conexao.Query<UsuarioModel>("INSERT INTO Usuario(nome,sobrenome,foto,email,telefone, dataCriacao,senha) values( @nome, @sobrenome,@foto,@email,@telefone, @dataCriacao,@senha)", new
            {
                nome = usuario.nome,
                sobrenome = usuario.sobrenome,
                email = usuario.email,
                foto="",
                telefone = usuario.telefone,
                endereco = usuario.endereco,
                senha=usuario.senha,
                dataCriacao= DateTime.Now
            });
            conexao.Close();

            return Redirect("/usuario/login");
        }
    }
}
    

PB_PETS/Views/Usuario/EditarPerfil.cshtml
@model PB_PETS.Models.UsuarioPerfilModel

<h5>Editar Perfil</h5>

<div >
        <div class="card" style="width: 38rem;margin-bottom:24px;position:relative;">
            
               @if (@Model.foto==null || Model.foto == "")
                {
                    
                    @using(Html.BeginForm("putFoto","Usuario", FormMethod.Post, new { enctype="multipart/form-data"}))
        {
                      <div style="display:flex;height:300px;align-items:center;justify-content:center;flex-direction:column">
                        @Html.TextBox("file", "", new {  type= "file"}) <br />        
                        <input  name="id" style="display:none;" value="@Model.Id"/>
                            <br/>
                        <button type="submit" class="btn btn-primary" style="margin-top:34px;">Atualizar</button>
                        @ViewBag.Message
                    </div>
                   }
                }
                else
                {   
                    <div>
                           <form action="/usuario/deleteFoto" method="post" style="position:absolute;top:0;right:0;">  
                                    <input name="Id" value=@Model.Id style="display:none;"/>
                                <button type="submit" class="btn btn-danger">Deletar</button>
                            </form>
                    <img class="card-img-top" src=@Model.foto alt="image profile">
                    </div>
                }
           
          <div class="card-body">
            <form action="/usuario/EditarPerfil" method="post">
                <input value=@Model.Id name="Id" style="display:none;"/>
                <div class="form-group">
                    <label for="exampleInputEmail1">Nome</label>
                    <input value=@Model.nome class="form-control" name ="nome" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Sobrenome</label>
                    <input  value=@Model.sobrenome class="form-control" name ="sobrenome" aria-describedby="emailHelp" placeholder="Enter email">
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" value=@Model.email class="form-control" name ="email" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Telefone</label>
                    <input value=@Model.telefone class="form-control" name ="telefone" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Endereco</label>
                    <input value=@Model.endereco class="form-control" name ="endereco" aria-describedby="emailHelp" placeholder="Enter email">
                </div>
              <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
            <h5 class="card-title">@Model.nome @Model.sobrenome</h5>
           
          </div>
        </div>
</div>

PB_PETS/Views/Usuario/EditarSenha.cshtml
@model PB_PETS.Models.EditarSenhaModel

<h5>Editar Senha</h5>

<div >
        <div class="card" style="width: 38rem;margin-bottom:24px;">
          <div class="card-body">
            <form action="/usuario/EditarSenha" method="post">
                <input value=@Model.Id name="Id" style="display:none;"/>
                <div class="form-group">
                    <label for="exampleInputEmail1">Senha atual</label>
                    <input required class="form-control" name ="senhaAtual" aria-describedby="emailHelp" value=@Model.senhaAtual>
                    @if(@Model.erroSenhaAtual == true){
                        <span style="color:red;">Senha atual invalida</span>
                    }
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Nova Senha</label>
                    <input required class="form-control" name ="senha" aria-describedby="emailHelp"value=@Model.senha >
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1">Confirme senha</label>
                    <input required  class="form-control" name ="senha2" aria-describedby="emailHelp" value=@Model.senha2>
                      @if(@Model.erroSenhaNova == true){
                        <span style="color:red;">Senhas nao conferem</span>
                    }
                </div>

              <button type="submit" class="btn btn-primary" >Editar senha</button>
            </form>
          </div>
        </div>
</div>

PB_PETS/Views/Usuario/Login.cshtml
<h1>Login</h1>
<div class="card">
<article class="card-body">
<h4 class="card-title mb-4 mt-1">Sign in</h4>
	     <form>
        <div class="form-group">
    	    <label>Your email</label>
            <input name="" class="form-control" placeholder="Email" type="email">
        </div> <!-- form-group// -->
        <div class="form-group">
    	    <a class="float-right" href="#">Forgot?</a>
    	    <label>Your password</label>
            <input class="form-control" placeholder="******" type="password">
        </div> <!-- form-group// --> 
        <div class="form-group"> 
        <div class="checkbox">
          <label> <input type="checkbox"> Save password </label>
        </div> <!-- checkbox .// -->
        </div> <!-- form-group// -->  
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block"> Login  </button>
        </div> <!-- form-group// -->                                                           
    </form>
</article>
</div>

PB_PETS/Views/Usuario/Perfil.cshtml
@model PB_PETS.Models.UsuarioPerfilModel

<h5>Perfil</h5>

<div >
        <div class="card" style="width: 38rem;margin-bottom:24px;">
               @if (@Model.foto!=null && Model.foto!="")
                {
                    <img class="card-img-top" src=@Model.foto alt="image profile"/>
                }
                else
                {   
                <img class="card-img-top" src="https://png.pngtree.com/png-vector/20190710/ourlarge/pngtree-user-vector-avatar-png-image_1541962.jpg" alt="image profile">
                }
}
          <div class="card-body">
              <div style="display:flex;flex-direction:row;justify-content:space-between;">
                  <h5 class="card-title">@Model.nome @Model.sobrenome</h5>
              @if (@Model.isMine ==false)
            {
                if (@Model.isSolicitado)
                {
                    if (@Model.isAmigo)
                    {
                        <form action="/amizade/recusar" method="post">
                            <input name="Id" value=@Model.idAmizade  style="display:none;"/>
                            <button class="btn btn-danger" style="margin-right:12px">Desfazer amizade</button>
                        </form>
                    }
                    else
                    {
                        <h6>Amizade solicitada</h6>
                    }
                }
                else
                {
                    <form action="/amizade/Adicionar" method="post">
                         <input style="display:none;" name="Id" value="@Model.Id" />
                         <button type="submit" class="btn btn-primary">Adicionar</button>
                    </form>

                }
            }
            else
            {
                <div style="display:flex;">
                    <a href="/usuario/editarSenha" style="margin-right:12px;"> Editar senha</a>
                 <a href="/usuario/editarperfil?id=@Model.Id">Editar Perfil</a>
                 </div>
            }
            
            </div>
            <div style='display:flex;flex-direction:row;justify-content:space-between;align-items:center;margin-bottom:12px;'>
                <h6 class="card-title">@Model.email</h6>
                <p>@Model.telefone</p>
                <p>@Model.endereco</p>

            </div>
          </div>
        </div>
</div>

PB_PETS/Views/Usuario/Register.cshtml
<div class="card">
<article class="card-body">
<h4 class="card-title mb-4 mt-1">Sign in</h4>
	 <form method="post" action="/usuario/register">
        <div class="form-group">
    	    <label>Nome</label>
            <input name="nome" class="form-control" placeholder="Email" required required>
        </div>
            <div class="form-group">
    	    <label>Sobrenome</label>
            <input name="sobrenome" class="form-control" placeholder="Email" required>
        </div>
            <div class="form-group">
    	    <label>Email</label>
            <input name="email" class="form-control" placeholder="Email" type="email">
        </div>
          <div class="form-group">
    	    <label>Telefone</label>
            <input name="telefone" class="form-control" placeholder="Email"required >
        </div>
         
    <div class="form-group">
    	    <label>Senha</label>
        <input class="form-control" placeholder="******" name="senha" type="password" required>
    </div> <!-- form-group// --> 
    
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> Registre-se  </button>
    </div> <!-- form-group// -->                                                           
</form>
</article>
</div> 