PB_PETS/Controllers/AmizadeController.cs
using Dapper;
using Microsoft.AspNetCore.Mvc;
using PB_PETS.Helpers;
using PB_PETS.Models;
using System.Data;

namespace PB_PETS.Controllers
{
    public class AmizadeController : Controller
    {
        private IDbConnection conexao;
        private LoggedUser loggedUser = new LoggedUser();
        public AmizadeController(IDbConnection conexao)
        {
            this.conexao = conexao;
        }

        [HttpPost]
        public ActionResult Adicionar(UsuarioModel usuario)
        {
            conexao.Open();
            conexao.Query("INSERT INTO Amizade (idUsuarioOrigem,idUsuarioDestino,dataCriacao) values (@idUsuarioOrigem,@idUsuarioDestino,@dataCriacao)", new { idUsuarioOrigem = loggedUser.getLoggedUser(), idUsuarioDestino = usuario.Id, dataCriacao = DateTime.Now });
            conexao.Close();
            return Redirect("/Usuario/perfil?Id=" + usuario.Id);
        }

        [HttpPost]
        public ActionResult Aceitar(AmizadeModel amizade)
        {
            conexao.Open();
            conexao.Query("UPDATE Amizade SET statusDaSolicitacao = 1 where Id = @id", new { id = @amizade.Id });
            conexao.Close();
            return RedirectToAction("listar");
        }

        [HttpPost]

        public ActionResult Recusar(AmizadeModel amizade)
        {
            conexao.Open();
            conexao.Query("DELETE Amizade where Id = @id", new { id = @amizade.Id });
            conexao.Close();
            return Redirect("listar");
        }


        public ActionResult Listar()
        {
            AmizadeList amizadeList = new AmizadeList();
            conexao.Open();

            var publicacoesAmigos = conexao.Query<PublicacaoUsuarioModel>("SELECT Usuario.foto as fotoUsuario,Publicacao.id as idPublicacao, Publicacao.texto,Publicacao.foto,Usuario.nome,Publicacao.dataCriacao FROM Publicacao INNER JOIN Usuario ON Usuario.Id = Publicacao.idUsuario WHERE idUsuario IN( SELECT idUsuarioDestino as Id FROM Amizade WHERE idUsuarioOrigem=@id AND statusDaSolicitacao = 1 UNION SELECT idUsuarioOrigem as Id FROM Amizade WHERE idUsuarioDestino=@id AND statusDaSolicitacao = 1)", new { id = loggedUser.getLoggedUser() });
            var i = 0;
            foreach (var publicacao in publicacoesAmigos)
            {
                publicacao.comentarios = (List<ComentarioUsuarioModel>)conexao.Query<ComentarioUsuarioModel>("SELECT * FROM Comentario INNER JOIN Usuario ON Usuario.Id=Comentario.idUsuario where Comentario.idPublicacao=@idPublicacao", new { idPublicacao = publicacao.idPublicacao });
                var curtidas = conexao.Query<CurtidaModel>("SELECT * FROM Curtidas where idPublicacao=@idPublicacao", new { idPublicacao = publicacao.idPublicacao });
                publicacao.curtidas = curtidas.Count();
                publicacao.isMine = publicacao.idUsuario == loggedUser.getLoggedUser() ? true : false;
                i++;
            };
            amizadeList.novasAmizades = conexao.Query<AmizadeModel>("SELECT Amizade.Id,Usuario.nome,Usuario.sobrenome,Amizade.dataCriacao FROM Amizade INNER JOIN Usuario ON Amizade.idUsuarioDestino=Usuario.Id  WHERE Amizade.idUsuarioDestino=@id and Amizade.statusDaSolicitacao=0", new { id = loggedUser.getLoggedUser() });
            amizadeList.postsAmigos = publicacoesAmigos;

            conexao.Close();
            return View(amizadeList);
        }
    } 
}

PB_PETS/Controllers/PublicacaoController.cs
using Azure.Storage.Blobs;
using Dapper;
using Microsoft.AspNetCore.Mvc;
using PB_PETS.Helpers;
using PB_PETS.Models;
using System.Data;

namespace PB_PETS.Controllers
{
    public class PublicacaoController : Controller
    {
        private IDbConnection conexao;
        private string blobConnectionString = "DefaultEndpointsProtocol=https;AccountName=rodstorage212121;AccountKey=J65S5+UoCngu3gx1f1NDTfAxUaOMH6REVKpw6ItRjUWNLpBW2KxImHeLAk2S7e6WvJ8RSlqgPpJs+ASta9ILMg==;EndpointSuffix=core.windows.net";
        private string containerName = "containerfinalpb";
        private string bucketUrl = "https://rodstorage212121.blob.core.windows.net/containerfinalpb";
        private LoggedUser loggedUser = new LoggedUser();


        public PublicacaoController(IDbConnection conexao)
        {
            this.conexao = conexao;
        }
        public ActionResult Listar()
        {
            conexao.Open();
            var publicacoes = conexao.Query<PublicacaoUsuarioModel>("select Publicacao.texto,Publicacao.foto , Publicacao.Id as idPublicacao, Publicacao.dataCriacao as publicacaoDataCriacao,Usuario.nome,Usuario.foto as fotoUsuario,Usuario.id as idUsuario from Publicacao INNER JOIN Usuario ON Publicacao.idUsuario=Usuario.Id ORDER BY publicacaoDataCriacao ASC");

            foreach (var publicacao in publicacoes)
            {
                publicacao.comentarios = (List<ComentarioUsuarioModel>)conexao.Query<ComentarioUsuarioModel>("SELECT * FROM Comentario INNER JOIN Usuario ON Usuario.Id=Comentario.idUsuario where Comentario.idPublicacao=@idPublicacao", new { idPublicacao = publicacao.idPublicacao });
                var curtidas = conexao.Query<CurtidaModel>("SELECT * FROM Curtidas where idPublicacao=@idPublicacao", new { idPublicacao = publicacao.idPublicacao });
                publicacao.curtidas = curtidas.Count();
                publicacao.isMine = publicacao.idUsuario == loggedUser.getLoggedUser() ? true : false;
            };

            conexao.Close();

            return View(publicacoes);
        }

        [HttpPost]
        public async Task<ActionResult> PublicarAsync()
        {
            var file = this.HttpContext.Request.Form.Files.FirstOrDefault();

            var dict = this.HttpContext.Request.Form.ToDictionary(x => x.Key, x => x.Value.ToString());
            string texto = dict["texto"];

            var foto = "";

            if (file != null)
            {
                if (file == null)
                {
                    return BadRequest();
                }
                else if (file.ContentType != "image/jpg" && file.ContentType != "image/png" && file.ContentType != "image/jpeg" && file.ContentType != "image/bmp" && file.ContentType != "image/gif")
                {
                    return BadRequest();
                }

                using (var stream = file.OpenReadStream())
                {
                    string fileName = Guid.NewGuid().ToString("N") + "." + file.ContentType.Split('/')[1];

                    // Conecta no Azure Blob Storage
                    BlobServiceClient client = new BlobServiceClient(blobConnectionString);
                    // Pega a referencia do container
                    var containerClient = client.GetBlobContainerClient(containerName);
                    // Cria a referencia do nome do arquivo
                    BlobClient blob = containerClient.GetBlobClient(fileName);
                    // Sobe para Azure
                    await blob.UploadAsync(stream);
                    foto = $"{bucketUrl}/{fileName}";
                }
            }

            conexao.Open();
            conexao.Query<PublicacaoModel>("INSERT INTO Publicacao (idUsuario,texto,foto,dataCriacao) values(@idUsuario,@texto,@foto,@dataCriacao)", new { idUsuario = loggedUser.getLoggedUser(), texto= texto,foto=foto,dataCriacao = DateTime.Now });
            conexao.Close();
            return Redirect("Listar");
        }


        [HttpPost]
        public ActionResult Comentar(ComentarioModel comentario)
        {
            conexao.Open();
            conexao.Query<ComentarioModel>("INSERT INTO Comentario (idUsuario,idPublicacao,texto,dataCriacao) values(@idUsuario,@idPublicacao,@texto,@dataCriacao)", new { idUsuario = loggedUser.getLoggedUser(), texto = comentario.texto, idPublicacao = comentario.idPublicacao, dataCriacao = DateTime.Now });
            conexao.Close();
            return Redirect("Listar");
        }


        [HttpPost]
        public ActionResult Curtir(PublicacaoModel publicacao)
        {
            conexao.Open();
            List<CurtidaModel>curtida = (List<CurtidaModel>)conexao.Query<CurtidaModel>("SELECT * FROM Curtidas where idPublicacao=@idPublicacao and idUsuario=@idUsuario", new { idPublicacao = publicacao.Id,idUsuario = loggedUser.getLoggedUser() });

            if(curtida.Count == 0)
            {
                conexao.Query<PublicacaoModel>("INSERT INTO Curtidas (idUsuario,idPublicacao,dataCriacao) values(@idUsuario,@idPublicacao,@dataCriacao)", new { idUsuario = loggedUser.getLoggedUser(), idPublicacao = publicacao.Id, dataCriacao = DateTime.Now });
            }
            else
            {
                conexao.Query<PublicacaoModel>("DELETE FROM Curtidas WHERE idPublicacao=@idPublicacao and idUsuario=@idUsuario", new { idUsuario = loggedUser.getLoggedUser(), idPublicacao = publicacao.Id, dataCriacao = DateTime.Now });
            }

            conexao.Close();
            return Redirect("Listar");
        }

        [HttpPost]
        public ActionResult Deletar(PublicacaoModel publicacao)
        {
            conexao.Open();
            conexao.Query<PublicacaoModel>("DELETE FROM Publicacao WHERE Id=@idPublicacao", new { idPublicacao = publicacao.Id});
            conexao.Close();
            return Redirect("Listar");
        }

        [HttpPost]
        public ActionResult putFoto(FotoModel publicacao)
        {
            conexao.Open();
            conexao.Query<PublicacaoModel>("UPDATE publicacao SET foto = @foto WHERE Id = @id", new { foto = publicacao.foto, id = publicacao.Id});
            conexao.Close();
            return Redirect("Listar");
        }
    }
}

PB_PETS/Views/Amizade/Listar.cshtml
@model AmizadeList

  <h2 style="margin-bottom:20px;margin-top:30px;">Novas Amizades: @Model.novasAmizades.Count()</h2>
      @foreach (var novaAmizade in Model.novasAmizades)
    {
        <div style="padding:8px;display:flex;align-items:center; border:1px solid black;">
            <form action="/amizade/aceitar" method="post">
                <input name="Id" value=@novaAmizade.Id  style="display:none;"/>
                <span style="margin-right:12px"><strong>@novaAmizade.nome @novaAmizade.sobrenome</strong> Quer te adicionar!</span>
                <button class="btn btn-primary" style="margin-right:12px">Adicionar</button>
            </form>
            <form action="/amizade/recusar" method="post">
                <input name="Id" value=@novaAmizade.Id  style="display:none;"/>
                <button class="btn btn-danger" style="margin-right:12px">Recusar</button>
            </form>
        </div>

    }
<h5>Listar Publicacoes de amigos</h5>

@using(Html.BeginForm("Publicar","Publicacao", FormMethod.Post, new { enctype="multipart/form-data"}))
{
      <div class="form-group" style="margin-bottom:84px;width:100%">
        @Html.TextBox("file", "", new {  type= "file"}) <br />        
        <label for="texto">Escreva o texto</label>
        <input  name="texto" class="form-control" id="exampleInputEmail1" placeholder="O que esta pensando?">
            <br/>
        <button type="submit" class="btn btn-primary" style="margin-top:34px;">Publicar</button>
        @ViewBag.Message
    </div>
}

<div > 
  
  
    @foreach (var publicacao in Model.postsAmigos)
    {
        <div class="card" style="width: 38rem;margin-bottom:24px;">
            @if(@publicacao.isMine != false)
            {
                <form action="/publicacao/Deletar" method="post" style="position:absolute;top:0;right:0;">  
                    <input name="Id" value=@publicacao.idPublicacao  style="display:none;"/>
                    <button type="submit" class="btn btn-danger">Deletar</button>
                </form>
            }
            @if (@publicacao.foto!= "" && @publicacao.foto != null)
            {
                <img class="card-img-top" src=@publicacao.foto alt="Card image cap">
            }
          <div class="card-body">
              <div style="display:flex; align-items:center;">
                    @if(@publicacao.fotoUsuario != null && @publicacao.fotoUsuario != "")
                    {
                        <img src=@publicacao.fotoUsuario style="height:40px;width:40px;border-radius:25px;margin-right:12px"/>
                    }
                <h5 class="card-title"><a href="/usuario/perfil?id=@publicacao.idUsuario">@publicacao.nome </a></h5>
            </div>

            <div style='display:flex;flex-direction:row;justify-content:space-between;align-items:center;margin-bottom:12px;'>
                <h6 class="card-title">@publicacao.curtidas Curtidas</h6>
                <form action="/publicacao/Curtir" method="post">  
                    <input name="Id" value=@publicacao.idPublicacao  style="display:none;"/>
                    <button type="submit" class="btn btn-dark">Curtir</button>
                </form>
            </div>
            <p class="card-text">@publicacao.texto</p>
          </div>
          <span style="margin-left:12px;">Comentarios:</span>
          <ul class="list-group list-group-flush">
             @foreach (var comentario in publicacao.comentarios)
                {
                    <li class="list-group-item">   
                        @if(@comentario.foto != null && @comentario.foto != "")
                            {                                
                                <img src=@comentario.foto style="height:20px;width:20px;border-radius:25px;margin-right:6px"/>
                            }
                        <strong><a href="/usuario/perfil?id=@comentario.idUsuario">@comentario.nome</a></strong>   @comentario.texto</li>
                }
          </ul>
            <form action="/publicacao/comentar" method="post">  
                <div class="form-group" style="display:flex;flex-direction:column;align-items:center;">
                   
                    <input  name="idPublicacao" value=@publicacao.idPublicacao style="display:none;">
                    <input  name="texto" class="form-control" id="exampleInputEmail1" placeholder="Novo comentario" style="margin-top:12px;">
                </div>
                <button type="submit" class="btn btn-primary">Comentar</button>
            </form>
        </div>
    }
</div>